site_name: Standard APIs Docs

plugins:
  - swagger-ui-tag

nav:
  - Home: index.md
  - APIs:
      - Search Company: search-company.md
      - Search Company (Try): swagger-ui.html
search-company.md

theme:
  name: readthedocs
