site_name: Standard APIs Docs

nav:
  - Home: index.md
  - API Reference: api.md

theme:
  name: readthedocs

extra_javascript:
  - https://unpkg.com/swagger-ui-dist/swagger-ui-bundle.js
  - https://unpkg.com/swagger-ui-dist/swagger-ui-standalone-preset.js

extra_css:
  - https://unpkg.com/swagger-ui-dist/swagger-ui.css
