site_name: Standard APIs Docs

nav:
  - Home: index.md
  - APIs:
      - Search Company: search-company.yaml
      - Full API Reference: api.md
plugins:
  - search
  - openapi

theme:
  name: readthedocs

extra_javascript:
  - https://unpkg.com/swagger-ui-dist/swagger-ui-bundle.js
  - https://unpkg.com/swagger-ui-dist/swagger-ui-standalone-preset.js

extra_css:
  - https://unpkg.com/swagger-ui-dist/swagger-ui.css
  - swagger-custom.css 
